### ISSUE TITLE
ROS2 Sample Stack on a Husarion ROSbot

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#101]
## Description

Within our lab, we want to run a full sample robot software stack on a Husarion ROSbot, to help our developers get a better sense for ROS2 workflows, and identify usability issues and bugs in ROS2.

It is planned for the "first deliverable" to go on for a while as we build small bits of the stack over time. This Epic should still have a concrete scope, even if it is planned to have a long time frame.

## Documents

TODO: identify the scope of this project and document

## Completion Criteria

* [ ] Developer can use cross-compile to  
* [ ] Robot can map the lab
* [ ] Robot can navigate between 2 points in the lab autonomously
* [ ] User can view a dashboard of robot status (battery, system metrics, navigations states...)

**Comment by thomas-moulard** [comment]
No plan to work on this.
