### ISSUE TITLE
Tracking progress of the QoS Compatilibity Callbacks Epic

### ISSUE THREAD

**Issue by jaisontj** [ros-tooling/aws-roadmap#125]
The implementation details of the related https://github.com/ros-tooling/aws-roadmap/issues/115 epic are documented at https://github.com/ros2/ros2/issues/822.

## List of PRs to be tracked towards handling middleware that don't support these callbacks:
- [x] https://github.com/ros2/rmw/pull/202
- [x] https://github.com/ros2/rmw_implementation/pull/88
- [x] https://github.com/ros2/rmw_fastrtps/pull/354
- [x] https://github.com/ros2/rmw_connext/pull/397
- [x] https://github.com/ros2/rmw_cyclonedds/pull/115
- [x] https://github.com/ros2/rcl/pull/600
- [x] https://github.com/ros2/rclcpp/pull/1026

## List of PRs to be tracked towards the https://github.com/ros-tooling/aws-roadmap/issues/115 epic:
- [x] https://github.com/ros2/rmw_connext/pull/398
- [x] https://github.com/ros2/rmw_cyclonedds/pull/125
- [x] https://github.com/ros2/rmw/pull/193
- [x] ~~https://github.com/ros2/rmw_opensplice/pull/294~~ (obsolete)
- [x] https://github.com/ros2/rcl/pull/535
- [x] https://github.com/ros2/rclcpp/pull/924
- [x] https://github.com/ros2/rclpy/pull/459
- [x] https://github.com/ros2/ros2cli/pull/410
- [x] https://github.com/ros2/demos/pull/416

**Comment by thomas-moulard** [comment]
Punted from sprint #11 to sprint #12 on 2020-02-03

**Comment by mm318** [comment]
This ticket is actually not the epic. The epic is at https://github.com/ros-tooling/aws-roadmap/issues/115.

**Comment by mm318** [comment]
Ideally, there are sprint points assigned to this ticket, but it is quite hard to accurately point.

If this story was about the initial implementation of incompatible QoS callbacks, it might be easy to point. But this story is about pushing the pull requests through, and it largely depends on the amount and type of upstream maintainer/reviewer feedback, which is highly variable.

**Comment by emersonknapp** [comment]
This is the whole purpose of "relative complexity" estimates instead of "absolute time" ones. `rmw` API changes should, based on our experience, have a higher relative complexity because we know they take a lot of care and consideration, whereas even if rclcpp may be more code, it's probably a lower relative complexity because by the time you're reviewing it, it's probably noncontroversial, there's much less uncertainty.

**Comment by emersonknapp** [comment]
And this ticket wouldn't have points, it's meant to track an Epic
