### ISSUE TITLE
[Epic] ROS 1 support in ROS 2 cross-compile

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/aws-roadmap#131]
## Description

We have two tools for ROS cross-compilation, the custom tool used in RoboMaker and the open source [cross-compile](https://github.com/ros-tooling/cross_compile) tool used in ROS 2. We want to add ROS 1 support to the ROS 2 tool, so that the ROS 1 tool can be decommissioned and users have the same experience irrespective of which ROS distro they use.

## Documents

ROS 2 [cross-compile](https://github.com/ros-tooling/cross_compile) tool

## Completion Criteria

* [x] ROS 2 cross-compile can compile ROS 1 source code
* [ ] [Tool does cross compilation instead of emulated build](https://github.com/ros-tooling/cross_compile/issues/69)
* [ ] ROS 1 cross-compile tool is deprecated
* [ ] RoboMaker [developer documentation](https://docs.aws.amazon.com/robomaker/latest/dg/gs-deploy.html) is updated

**Comment by prajakta-gokhale** [comment]
Related tasks:
* [ ] SIM/ARF-5047
* [ ] SIM/ARF-5048
* [ ] SIM/ARF-5198
