### ISSUE TITLE
As a rosbag2 windows developer, I want to have stable E2E test so that I know my features work and are stable

### ISSUE THREAD

**Issue by piraka9011** [ros-tooling/aws-roadmap#178]
## Description

A regression was discovered in rosbag2 where E2E tests were not running in the CI and Windows builds were failing. The E2E tests need to be fixed. This issue tracks progress and bugs fixed:

**Recording E2E tests**

* [x] SQLite error codes unclear: ros2/rosbag2#269
* [x] Windows tests clean up after themselves: ros2/rosbag2#278
* [x] Ensure filesystem is in sync with tests: ros2/rosbag2#278
* [x] Stricter Compression checks: ros2/rosbag2#279
* [x] Recording with compression filesystem sync.

## Acceptance Criteria

* [x] E2E tests and CI for all rosbag2 packages on all systems pass.

Once all above items are checked, this story can be moved to done.

## Resources

* [Bag recorded on 32bit ARM is not readable](https://github.com/ros2/rosbag2/issues/153)

**Comment by emersonknapp** [comment]
This seems to have met its purpose, any remaining bugs are open in the appropriate location
