### ISSUE TITLE
rosbag2 compression

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#20]
## Description

Provide capability to compress and decompress ROS2 rosbags, similar to ROS1.

## Documents
https://github.com/ros-security/aws-roadmap/blob/master/spike-findings/15-rosbag2-compression.md

## Test Plan

Unit, integration, and end to end test. This is a good candidate to provide contributions to ROS2 system tests.

## Documentation Plan

Bulk of the documentation should live in the github readme and design docs.

## Release Plan

Next major ROS2 release.

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Subtasks
* [x] investigate compression algorithm performance with an example rosbag2
    * [x] make investigation document public (github page)

**Comment by emersonknapp** [comment]
This epic is complete
