### ISSUE TITLE
Prototype running RViz on ignition-rendering

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#30]
## Description

The purpose of this story is to create a PoC for the ignition rendering engine in Rviz. 
Rviz currently uses Ogre and we need to port the rendering functions used into ignition.
Specifically, the functions/interfaces in [`rviz_rendering`](https://github.com/ros2/rviz/tree/ros2/rviz_rendering/src/rviz_rendering) need to be refactored to use the Ignition API.
There are some Ogre specific implementations that need to be refactored accordingly using the Ignition complement.

A completed PoC demonstrates that rviz compiles and can be run with the Ignition backend.

## Test Plan

Document manual steps demonstrating how to compile and run `rviz` using an Ignition rendering backend.

## Documentation Plan

Write an internal document

## Release Plan

No Release since this is a PoC. Demo to PMs (who) and RViz stakeholders

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [ROS2 rviz_rendering](https://github.com/ros2/rviz/tree/ros2/rviz_rendering/src/rviz_rendering)

**Comment by emersonknapp** [comment]
No longer a priority
