### ISSUE TITLE
ROS2 System Metrics First Release

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#4]
## Description

Create a ROS2 system runtime metrics collection node and release it. 

The goal of this epic is to get a first version of a tool out there and in the hands of customers, to start driving feature asks. 

This first release will have fairly minimal features, so that we can be informed by feature requests to drive architecting for extensibility going forward.

## Documents

REMOVE ME: Link or include any designs that inform this Epic's completion criteria.

## Completion Criteria

* [x] A Metrics message type and topic name have been defined
* [x] A node collects and emits the following metrics, with their relevant statistics, i.e., min, max stddev, average, count
  * System CPU %
  * System Virtual Memory Used
  * Composeable nodes measuring the PID CPU % and Virtual % used
* [ ] The new package containing this node has been released via bloom

**Comment by emersonknapp** [comment]
Talking about first writing this as a no-API node release. Following best practices and architecting to a high standard internally, with the idea that we may make the necessary interfaces public later. Keeping it as a single binary is a one-way door, we can always expose more later.

**Comment by emersonknapp** [comment]
This original epic is complete, ongoing work on system metrics is beyond this epic's scope
