### ISSUE TITLE
Prototype opaque web-based rmw communication

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#43]
## Description

As part of the RViz Anywhere project, the WASM frontend of the visualizer needs to communicate with a native backend somewhere else.

One crucial phase of discovery towards this goal is to prototype that communications layer.

While building this PoC, we need to begin to identify what "good enough" will look like for communication performance, and get a baseline with this implementation. 

## Completion Criteria

* [ ] Native side communication bridge
* [ ] WASM side communication layer
* [ ] Define a first pass at meaningful metrics around performance
* [ ] Instrument a check for those metrics so we can test future POCs/implementations

**Comment by emersonknapp** [comment]
Not relevant
