### ISSUE TITLE
RViz2 Stability Pass 1

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#61]
## Description

As a robotics developer, I want to use rviz so that I can visualize my robot, similar to ROS1, without
crashing.

There have been reports of crashes in RViz2, which is a customer problem, and blocks us from building any new features around RViz that we are planning. 

In the interest of creating a scope for this, and in the absence of details from above, we are scraping the existing RViz crash bugs as the scope for this Epic.

Not all of them may be resolvable by our team, but we should give each one that doesn't have an current assignee a best-effort pass.

## Completion Criteria

* [ ] Talk with users who gave us feedback that rviz2 is crashing
* [ ] Fill bugs for all of their crashes
* [ ] Fix the reported bugs for the allocated amount of time (4 weeks), according to importance

## Existing bugs
*Do not solve those directly, talk to customers first, and compare to the opened bugs*

* [ ] https://github.com/ros2/rviz/issues/458
* [ ] https://github.com/ros2/rviz/issues/442
* [ ] https://github.com/ros2/rviz/issues/368
* [ ] https://github.com/ros2/rviz/issues/322
* [ ] https://github.com/ros2/rviz/issues/291
* [ ] https://github.com/ros2/rviz/issues/224
* [ ] https://github.com/ros2/rviz/issues/146
* used this search https://github.com/ros2/rviz/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+crash+ - but we should lock in scope here for this Epic

**Comment by emersonknapp** [comment]
this is no longer an immediate priority
